services:
  - type: web
    name: chatroom
    env: node
    buildCommand: npm install && npm run build
    startCommand: node build
    envVars:
      - key: NODE_ENV
        value: production
      - key: ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
